name: Push Slack Notificartion
description: Call after a completed build to notify the appropriate slack channel (prod or nonprod)

inputs:
  app_name:
    description: 'Application Name'
    required: false
  repo_name:
    description: 'Repo Name'
    required: false
  git_branch:
    description: 'Git Branch'
    required: false
  git_sha:
    description: 'Short Commit SHA'
    required: false
  deploy_env:
    description: 'Deployment Environment (dev, stage, prod)'
    required: false
  deploy_url:
    description: 'Application url'
    required: false
  prod_deploy:
    description: 'Is this a production deployment?'
    required: true
    default: false
  slack_url:
    description: 'Channel to post update'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
        REPO_NAME=$(echo '${{ inputs.app_name }}' | awk -F '/' '{print $2}')
    - name: build slack message
      shell: bash
      run: |
        PAYLOAD="{
          \"blocks\":[
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*${{ inputs.repo_name }} ${{ inputs.git_branch }} Build Deployment*\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"$REPO_NAME version ${{ inputs.git_sha }} deployed to ${{ inputs.git_branch }} environment\"}},
            {\"type\":\"divider\"},
            {\"type\":\"actions\",\"elements\":[{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\"${{ inputs.git_sha }} on Github\",\"emoji\":true},\"value\":\"click_me_123\",\"url\":\"https:\/\/github.com\/${{ inputs.app_name }}\/commit\/${{ inputs.git_sha }}\"},
            {\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\"Go to main\",\"value\":\"www.google.com\",\"url\":\"${{ inputs.deploy_url }}\"}]}
         ]
        }"

        echo $PAYLOAD
        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" ${{ inputs.slack_url }}
    